# Generated by Django 3.1.4 on 2020-12-14 13:23

from django.db import migrations, models
import urlShortner.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortner', '0002_auto_20201214_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=16, validators=[urlShortner.models.validate_length]),
        ),
    ]
