# Generated by Django 3.1.4 on 2020-12-15 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortner', '0003_auto_20201214_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorturl',
            name='last_visited',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
