# Generated by Django 3.1.4 on 2020-12-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortner', '0004_auto_20201215_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=16),
        ),
    ]
